// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc711.Alev1;

import org.usfirst.frc711.Alev1.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc711.Alev1.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystickButton1;
    public Joystick joystick1;
    public JoystickButton joystickButton2;
    public JoystickButton joystickButton3;
    public static JoystickButton joystickButton4;
    public static JoystickButton joystickButton5;
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick1 = new Joystick(0);
        
        joystickButton1 = new JoystickButton(joystick1, 1);
        joystickButton1.whileHeld(new StopCommand());
        joystickButton2 = new JoystickButton(joystick1, 5);
        joystickButton2.whileHeld(new GearShift(1));
		joystickButton3 = new JoystickButton(joystick1, 6);
		joystickButton3.whileHeld(new GearShift(2));
		joystickButton4 = new JoystickButton(joystick1, 5);
		joystickButton5 = new JoystickButton(joystick1, 6);
		
		
		


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new DriveForwardCommand(10000));
        SmartDashboard.putData("Drive Command", new DriveCommand());
        SmartDashboard.putData("Stop Command", new StopCommand());
        SmartDashboard.putData("Elevator Command", new MoveElevator());
        SmartDashboard.putData("Intake Command", new MoveIntake());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        joystick1.setYChannel(5);
    	joystick1.setXChannel(1);
    	joystick1.setTwistChannel(2);
    	joystick1.setThrottleChannel(3);
    
    	
    	
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

