// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc711.Alev1;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTalonSRX1;
    public static WPI_TalonSRX driveTalonSRX2;
    public static WPI_TalonSRX driveTalonSRX3;
    public static SpeedControllerGroup driveLeft;
    public static WPI_TalonSRX driveTalonSRX4;
    public static WPI_TalonSRX driveTalonSRX5;
    public static WPI_TalonSRX driveTalonSRX6;
    public static SpeedControllerGroup driveRight;
    public static DoubleSolenoid driveDoubleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTalonSRX1 = new WPI_TalonSRX(1);
        
        
        driveTalonSRX2 = new WPI_TalonSRX(2);
        
        
        driveTalonSRX3 = new WPI_TalonSRX(3);
        
        
        driveLeft = new SpeedControllerGroup(driveTalonSRX1, driveTalonSRX2 , driveTalonSRX3 );
        LiveWindow.addActuator("Drive", "Left", driveLeft);
        
        driveTalonSRX4 = new WPI_TalonSRX(4);
        
        
        driveTalonSRX5 = new WPI_TalonSRX(5);
        
        
        driveTalonSRX6 = new WPI_TalonSRX(6);
        
        
        driveRight = new SpeedControllerGroup(driveTalonSRX4, driveTalonSRX5 , driveTalonSRX6 );
        LiveWindow.addActuator("Drive", "Right", driveRight);
        
        driveDoubleSolenoid = new DoubleSolenoid(0,0,1);
        LiveWindow.addActuator("Drive", "Double Solenoid", driveDoubleSolenoid);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveRight.setInverted(true);
    }
}
