// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc711.Alev1;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTalonSRX1;
    public static WPI_TalonSRX driveTalonSRX2;
    public static WPI_TalonSRX driveTalonSRX3;
    public static SpeedControllerGroup driveLeft;
    public static WPI_TalonSRX driveTalonSRX4;
    public static WPI_TalonSRX driveTalonSRX5;
    public static WPI_TalonSRX driveTalonSRX6;
    public static SpeedControllerGroup driveRight;
    public static DoubleSolenoid driveDoubleSolenoid;
    public static Compressor driveCompressor1;
    public static Encoder driveQuadratureEncoder1;
    public static PIDController drivePIDController1;
    public static SpeedController elevator1;
    public static SpeedController elevator2;
    public static SpeedControllerGroup elevatorSpeedControllerGroup1;
    public static DigitalInput elevatorLimitSwitch1;
    public static DigitalInput elevatorLimitSwitch2;
    public static SpeedController intake1;
    public static SpeedController intake2;
    public static SpeedControllerGroup intakeSpeedControllerGroup1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTalonSRX1 = new WPI_TalonSRX(1);
        
        
        driveTalonSRX2 = new WPI_TalonSRX(2);
        
        
        driveTalonSRX3 = new WPI_TalonSRX(3);
        
        
        driveLeft = new SpeedControllerGroup(driveTalonSRX1, driveTalonSRX2 , driveTalonSRX3 );
        LiveWindow.addActuator("Drive", "Left", driveLeft);
        
        driveTalonSRX4 = new WPI_TalonSRX(4);
        
        
        driveTalonSRX5 = new WPI_TalonSRX(5);
        
        
        driveTalonSRX6 = new WPI_TalonSRX(6);
        
        
        driveRight = new SpeedControllerGroup(driveTalonSRX4, driveTalonSRX5 , driveTalonSRX6 );
        LiveWindow.addActuator("Drive", "Right", driveRight);
        
        driveDoubleSolenoid = new DoubleSolenoid(0,0,1);
        LiveWindow.addActuator("Drive", "Double Solenoid", driveDoubleSolenoid);
        
        elevator1 = new Spark(0);
        LiveWindow.addActuator("Elevator", "Elevator 1", (Spark) elevator1);
        elevator1.setInverted(false);
        elevator2 = new Spark(1);
        LiveWindow.addActuator("Elevator", "Elevator 2", (Spark) elevator2);
        elevator2.setInverted(false);
        elevatorSpeedControllerGroup1 = new SpeedControllerGroup(elevator1, elevator2  );
        LiveWindow.addActuator("Elevator", "Speed Controller Group 1", elevatorSpeedControllerGroup1);
        
        intake1 = new Spark(2);
        intake1.setInverted(true);
        intake2 = new Spark(3);
        intake2.setInverted(false);
        intakeSpeedControllerGroup1 = new SpeedControllerGroup(intake1, intake2  );
        LiveWindow.addActuator("intake", "Speed Controller Group 2", intakeSpeedControllerGroup1);
        
        elevatorLimitSwitch1 = new DigitalInput(0);
        elevatorLimitSwitch2 = new DigitalInput(1);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveRight.setInverted(true);
        elevatorSpeedControllerGroup1.setInverted(true);
    }
}
